### ISSUE TITLE
Migrating from macOS to Docker Compose

### ISSUE THREAD

**Issue by rodrigopolo** [MMMZZZZ/Jellyfin-Migrator#18]
This is NOT an issue, it is a small guide to show how to migrate from the Jellyfin desktop app for macOS to a Docker installation.

I had an external drive with all my media, ej: `/Volumes/ExternalDrive/AllMyMedia`, this path had inside the TV Shows, Movies, etc. So, I have to replicate that path in order for Jellyfin to recognize the original path, here is my `docker-compose.yml` file:

```yaml
---
services:
    jellyfin:
        image: lscr.io/linuxserver/jellyfin:latest
        container_name: jellyfin
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
        volumes:
            - ./config:/config
            - /ExternalPathTo/AllMyMedia:/Volumes/ExternalDrive/AllMyMedia
            # - ./data/tvshows:/data/tvshows
            # - ./data/movies:/data/movies
        ports:
            - 8096:8096
            #- 8920:8920 #optional
            #- 7359:7359/udp #optional
            #- 1900:1900/udp #optional
        restart: always
```

After creating the `docker-compose.yml` file into its directory, I run the container:

```sh
docker compose pull
docker compose up -d
```

Then I create the default user in the web interface, and skip the library creation, the deal is to just have Jellyfin running after the installation, and after passing the setup wizard, with a user working, I stop the container:

```sh
docker compose stop
```

Then I copy the original Jellyfin configuration files that are in the macOS system where Jellyfin was installed, into the directory where the `docker-compose.yml` was created:

```sh
# Copy the Jellyfin data, metadata, plugins, root and transcodes folders
cp -r \
~/.local/share/jellyfin/data \
~/.local/share/jellyfin/metadata \
~/.local/share/jellyfin/plugins \
~/.local/share/jellyfin/root \
~/.local/share/jellyfin/transcodes \
./config/data/.

# Copy the Jellyfin cache folder
cp -r \
~/.cache/jellyfin \
./config/cache

# Copy the Jellyfin log folder
cp -r \
~/.local/share/jellyfin/log \
./config/.
```

Then, I start the container
```sh
docker compose up -d
```

And that's it, you can login and expect the very same experience as the desktop app, hope it helps someone out there.
